# Generated by Django 4.1.2 on 2022-11-09 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_Name', models.CharField(max_length=150)),
                ('State_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.state')),
            ],
        ),
    ]
