# Generated by Django 4.1.2 on 2022-10-16 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Name', models.CharField(error_messages={'max_length': 'Maximum Length is 30!'}, max_length=30)),
                ('Sender_Email', models.CharField(error_messages={'max_length': 'Maximum Length is 30!'}, max_length=30)),
                ('Sender_Name', models.CharField(error_messages={'max_length': 'Maximum Length is 30!'}, max_length=30)),
                ('SMTP_Host', models.CharField(error_messages={'max_length': 'Maximum Length is 30!'}, max_length=30)),
                ('SMTP_User', models.CharField(error_messages={'max_length': 'Maximum Length is 30!'}, max_length=30)),
                ('SMTP_Password', models.CharField(error_messages={'max_length': 'Maximum Length is 30!'}, max_length=30)),
                ('SMTP_Port', models.IntegerField()),
                ('Default_Server', models.CharField(error_messages={'max_length': 'Maximum Length is 30!'}, max_length=30)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Leave', models.CharField(max_length=30)),
                ('Days', models.IntegerField()),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Noti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Employee', models.BooleanField(error_messages={'required': 'Please Grant the Permission'})),
                ('Holidays', models.BooleanField(error_messages={'required': 'Please Grant the Permission'})),
                ('Leaves', models.BooleanField(error_messages={'required': 'Please Grant the Permission'})),
                ('Events', models.BooleanField(error_messages={'required': 'Please Grant the Permission'})),
                ('Chat', models.BooleanField(error_messages={'required': 'Please Grant the Permission'})),
                ('Jobs', models.BooleanField(error_messages={'required': 'Please Grant the Permission'})),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Office_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('In', models.TimeField()),
                ('Out', models.TimeField()),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Roles', models.CharField(choices=[('Administrator', 'Administrator'), ('CEO', 'CEO'), ('Manager', 'Manager'), ('Team Leader', 'Team Leader'), ('Accountant', 'Accountant'), ('Web Developer', 'Web Developer'), ('Web Designer', 'Web Designer'), ('HR', 'HR'), ('UI/UX Developer', 'UI/UX Developer'), ('SEO Analyst', 'SEO Analyst')], default='Select', max_length=30)),
                ('Grant_Employee', models.BooleanField()),
                ('Em_Create', models.BooleanField()),
                ('Em_Write', models.BooleanField()),
                ('Em_Read', models.BooleanField()),
                ('Em_Delete', models.BooleanField()),
                ('Grant_Holidays', models.BooleanField()),
                ('H_Create', models.BooleanField()),
                ('H_Write', models.BooleanField()),
                ('H_Read', models.BooleanField()),
                ('H_Delete', models.BooleanField()),
                ('Grant_Leaves', models.BooleanField()),
                ('L_Create', models.BooleanField()),
                ('L_Write', models.BooleanField()),
                ('L_Read', models.BooleanField()),
                ('L_Delete', models.BooleanField()),
                ('Grant_Events', models.BooleanField()),
                ('E_Create', models.BooleanField()),
                ('E_Write', models.BooleanField()),
                ('E_Read', models.BooleanField()),
                ('E_Delete', models.BooleanField()),
                ('Grant_Chat', models.BooleanField()),
                ('C_Create', models.BooleanField()),
                ('C_Write', models.BooleanField()),
                ('C_Read', models.BooleanField()),
                ('C_Delete', models.BooleanField()),
                ('Grant_Jobs', models.BooleanField()),
                ('J_Create', models.BooleanField()),
                ('J_Write', models.BooleanField()),
                ('J_Read', models.BooleanField()),
                ('J_Delete', models.BooleanField()),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('DA_HRA', models.BooleanField()),
                ('DA', models.IntegerField(blank=True, null=True)),
                ('HRA', models.IntegerField(blank=True, null=True)),
                ('PF', models.BooleanField()),
                ('Emp_Share', models.IntegerField(blank=True, null=True)),
                ('Org_Share', models.IntegerField(blank=True, null=True)),
                ('ESI', models.BooleanField()),
                ('E_Share', models.IntegerField(blank=True, null=True)),
                ('O_Share', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Theme_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Web_Name', models.CharField(error_messages={'max_length': 'Maximum Length is 50!'}, max_length=50)),
                ('Logo', models.ImageField(upload_to='picture/')),
                ('Favicon', models.ImageField(upload_to='picture/')),
                ('Login', models.ImageField(upload_to='picture/')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Date_Format', models.CharField(choices=[('15/05/2016', '15/05/2016'), ('15.05.2016', '15.05.2016'), ('15-05-2016', '15-05-2016'), ('05/15/2016', '05/15/2016'), ('2016/05/15', '2016/05/15'), ('2016-05-15', '2016-05-15'), ('15 May 2016', '15 May 2016'), ('May 15 2016', 'May 15 2016')], default='Select', max_length=30)),
                ('Timezone', models.CharField(choices=[('(UTC +5:30) Antarctica/Palmer', '(UTC +5:30) Antarctica/Palmer')], default='Select', max_length=30)),
                ('Language', models.CharField(choices=[('Tamil', 'Tamil'), ('English', 'English'), ('French', 'French')], default='Select', max_length=30)),
                ('Currency_Code', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('Pound', 'Pound'), ('EURO', 'EURO')], default='Select', max_length=30)),
                ('Currency_Symbol', models.CharField(default='$', max_length=30)),
                ('Country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master.countries')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company_Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Company_Name', models.CharField(error_messages={'max_length': 'Maximum Char 50!.'}, max_length=50)),
                ('Contact_Person', models.CharField(error_messages={'max_length': 'Maximum Char 50!.'}, max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('Postal_Code', models.IntegerField()),
                ('Email', models.EmailField(error_messages={'unique': 'The Email Field already used.'}, max_length=70, unique=True)),
                ('Phone_Number', models.CharField(max_length=10)),
                ('Website_URL', models.URLField()),
                ('Country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master.countries')),
                ('State', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master.state')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
